<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Wcs.Core\Wcs.Core.csproj" />
    <ProjectReference Include="..\Wcs.ModelOps\Wcs.ModelOps.csproj" />
    <ProjectReference Include="..\Wcs.FeatureCenter\Wcs.FeatureCenter.csproj" />
    <ProjectReference Include="..\Wcs.DecisionIntelligence\Wcs.DecisionIntelligence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.28.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="S7netplus" Version="0.20.0" />
    <PackageReference Include="Serilog" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>