<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Wcs.Host-73d4c62e-b7b4-423b-877d-fa4601e72fff</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Wcs.Entity\Wcs.Entity.csproj" />
    <ProjectReference Include="..\..\Wcs.Service\Wcs.Service.csproj" />
    <ProjectReference Include="..\Wcs.Core\Wcs.Core.csproj" />
    <ProjectReference Include="..\Wcs.Infrastructure\Wcs.Infrastructure.csproj" />
    <ProjectReference Include="..\Wcs.Application\Wcs.Application.csproj" />
    <ProjectReference Include="..\Wcs.Simulator\Wcs.Simulator.csproj" />
  </ItemGroup>
</Project>
