<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wcs.FeatureCenter\Wcs.FeatureCenter.csproj" />
    <ProjectReference Include="..\Wcs.ModelOps\Wcs.ModelOps.csproj" />
  </ItemGroup>
</Project>
