using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Wcs.Entity;

namespace Wcs.Service
{
    public class LoadService
    {
        public List<MenuItemDto> GetStaticMenus()
        {
            // 注意：此处直接将你提供的 JSON 数据硬编码，正式项目应替换为数据库查询
            return new List<MenuItemDto>
            {
                new MenuItemDto { Id = 8, Name = "图表开发", Url = "/ProductionState", ParentId = 32, Icon = "el-icon-monitor", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 2, Name = "用户管理", Url = null, ParentId = 61, Icon = "el-icon-user", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 235, Name = "MES业务", Url = "", ParentId = 0, Icon = "el-icon-monitor", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 291, Name = "菜单设置", Url = "", ParentId = 61, Icon = "el-icon-folder", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 62, Name = "菜单设置", Url = "/sysmenu", ParentId = 291, Icon = "", Enable = 1, TableName = "Sys_Menu", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 292, Name = "数据字典", Url = "", ParentId = 61, Icon = "el-icon-receiving", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 63, Name = "数据字典", Url = "/Sys_Dictionary", ParentId = 292, Icon = "", Enable = 1, TableName = "Sys_Dictionary", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 133, Name = "审批管理", Url = "", ParentId = 61, Icon = "el-icon-mobile", Enable = 1, TableName = "流程管理", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 106, Name = "表单设计", Url = "", ParentId = 61, Icon = "el-icon-postcard", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 247, Name = "审批流程", Url = "", ParentId = 235, Icon = "el-icon-date", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 142, Name = "组织架构", Url = "/Sys_Department", ParentId = 2, Icon = "", Enable = 1, TableName = "Sys_Department", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 236, Name = "基础设置", Url = "", ParentId = 235, Icon = "el-icon-receiving", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 296, Name = "图表统计", Url = "", ParentId = 32, Icon = "el-icon-data-line", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 9, Name = "用户管理", Url = "/Sys_User", ParentId = 2, Icon = "", Enable = 1, TableName = "Sys_User", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import", "Export", "Upload", "Audit" } },
                new MenuItemDto { Id = 237, Name = "仓库管理", Url = "", ParentId = 235, Icon = "el-icon-house", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 293, Name = "消息推送", Url = "", ParentId = 61, Icon = "el-icon-chat-dot-round", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 137, Name = "定时任务", Url = "", ParentId = 61, Icon = "el-icon-alarm-clock", Enable = 1, TableName = "定时任务", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 32, Name = "基础组件", Url = "", ParentId = 0, Icon = "el-icon-full-screen", Enable = 1, TableName = "/", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 132, Name = "消息推送", Url = "/signalR", ParentId = 293, Icon = "el-icon-chat-line-round", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 238, Name = "设备管理", Url = "", ParentId = 235, Icon = "el-icon-news", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 241, Name = "工序管理", Url = "", ParentId = 235, Icon = "el-icon-mobile-phone", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 64, Name = "代码生成", Url = "/coding", ParentId = 61, Icon = "el-icon-paperclip", Enable = 1, TableName = "代码生成", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 239, Name = "生产计划", Url = "", ParentId = 235, Icon = "el-icon-shopping-cart-1", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 286, Name = "制造BOM", Url = "", ParentId = 235, Icon = "el-icon-setting", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 244, Name = "生产报工", Url = "", ParentId = 235, Icon = "el-icon-tickets", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 5, Name = "日志管理", Url = "/", ParentId = 61, Icon = "el-icon-date", Enable = 1, TableName = "xxx", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 240, Name = "质检中心", Url = "", ParentId = 235, Icon = "el-icon-edit-outline", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 242, Name = "生产排班", Url = "", ParentId = 235, Icon = "el-icon-stopwatch", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 71, Name = "权限管理", Url = "/permission", ParentId = 2, Icon = "ivu-icon ivu-icon-ios-boat", Enable = 1, TableName = ",", Permission = new List<string> { "Search", "Update" } },
                new MenuItemDto { Id = 61, Name = "系统设置", Url = "/", ParentId = 0, Icon = "el-icon-setting", Enable = 1, TableName = "系统设置", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 271, Name = "生产报工", Url = "/MES_ProductionReporting", ParentId = 244, Icon = "", Enable = 1, TableName = "MES_ProductionReporting", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Audit", "AntiAudit", "Print" } },
                new MenuItemDto { Id = 275, Name = "质量检验", Url = "/MES_QualityInspectionPlan", ParentId = 240, Icon = "", Enable = 1, TableName = "MES_QualityInspectionPlan", Permission = new List<string> { "Search", "Add", "Delete", "Update", "CopyData", "Export" } },
                new MenuItemDto { Id = 267, Name = "生产订单", Url = "/MES_ProductionOrder", ParentId = 239, Icon = "", Enable = 1, TableName = "MES_ProductionOrder", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export", "Print" } },
                new MenuItemDto { Id = 260, Name = "设备管理", Url = "/MES_EquipmentManagement", ParentId = 238, Icon = "", Enable = 1, TableName = "MES_EquipmentManagement", Permission = new List<string> { "Search", "Add", "Delete", "Update" } },
                new MenuItemDto { Id = 255, Name = "仓库管理", Url = "/MES_WarehouseManagement", ParentId = 237, Icon = "", Enable = 1, TableName = "MES_WarehouseManagement", Permission = new List<string> { "Search", "Add", "Delete", "Update", "CopyData", "Import", "Export" } },
                new MenuItemDto { Id = 36, Name = "图表+表单", Url = "/formChart", ParentId = 32, Icon = "el-icon-data-analysis", Enable = 1, TableName = "/", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 3, Name = "角色管理", Url = "/Sys_Role", ParentId = 2, Icon = "", Enable = 1, TableName = "Sys_Role", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 295, Name = "生产统计", Url = "/ProductionState", ParentId = 294, Icon = "", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 281, Name = "我的审批", Url = "/Sys_WorkFlowTable", ParentId = 247, Icon = "", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 272, Name = "报工明细", Url = "/MES_ProductionReportingDetail", ParentId = 244, Icon = "", Enable = 2, TableName = "MES_ProductionReportingDetail", Permission = new List<string> { "Search", "Add", "Delete" } },
                new MenuItemDto { Id = 279, Name = "排班计划", Url = "/MES_SchedulingPlan", ParentId = 242, Icon = "", Enable = 1, TableName = "MES_SchedulingPlan", Permission = new List<string> { "Search", "Add", "Delete", "Update", "CopyData", "Export" } },
                new MenuItemDto { Id = 264, Name = "工序管理", Url = "/MES_Process", ParentId = 241, Icon = "", Enable = 1, TableName = "MES_Process", Permission = new List<string> { "Search", "Add", "Delete", "Update", "CopyData", "Print" } },
                new MenuItemDto { Id = 261, Name = "设备维修", Url = "/MES_EquipmentRepair", ParentId = 238, Icon = "", Enable = 1, TableName = "MES_EquipmentRepair", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import", "Export" } },
                new MenuItemDto { Id = 256, Name = "货位管理", Url = "/MES_LocationManagement", ParentId = 237, Icon = "", Enable = 1, TableName = "MES_LocationManagement", Permission = new List<string> { "Search", "Add", "Delete", "Update", "CopyData", "Import", "Export" } },
                new MenuItemDto { Id = 249, Name = "客户管理", Url = "/MES_Customer", ParentId = 236, Icon = "", Enable = 1, TableName = "MES_Customer", Permission = new List<string> { "Search", "Add", "Delete", "Update" } },
                new MenuItemDto { Id = 91, Name = "图表+表格", Url = "/flex", ParentId = 32, Icon = "el-icon-odometer", Enable = 1, TableName = "数字排版", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 299, Name = "文本编辑", Url = "", ParentId = 32, Icon = "el-icon-mobile-phone", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 300, Name = "主从结构", Url = "/MES_Process", ParentId = 32, Icon = "el-icon-office-building", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import" } },
                new MenuItemDto { Id = 301, Name = "树形结构", Url = "/MES_Material", ParentId = 32, Icon = "el-icon-guide", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import" } },
                new MenuItemDto { Id = 298, Name = "一对多配置", Url = "", ParentId = 32, Icon = "el-icon-coin", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 282, Name = "流程配置", Url = "Sys_WorkFlow", ParentId = 247, Icon = "", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Add", "Delete", "Update" } },
                new MenuItemDto { Id = 265, Name = "工线路线", Url = "/MES_ProcessRoute", ParentId = 241, Icon = "", Enable = 1, TableName = "MES_ProcessRoute", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 257, Name = "库存管理", Url = "/MES_InventoryManagement", ParentId = 237, Icon = "", Enable = 1, TableName = "MES_InventoryManagement", Permission = new List<string> { "Search", "CopyData", "Export", "Print" } },
                new MenuItemDto { Id = 250, Name = "供应商", Url = "/MES_Supplier", ParentId = 236, Icon = "", Enable = 1, TableName = "MES_Supplier", Permission = new List<string> { "Search", "Add", "Delete", "Update", "CopyData", "Import", "Export" } },
                new MenuItemDto { Id = 294, Name = "统计报表", Url = "", ParentId = 235, Icon = "el-icon-data-line", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 297, Name = "多页签配置", Url = "", ParentId = 32, Icon = "el-icon-receiving", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 273, Name = "生产不良记录", Url = "/MES_DefectiveProductRecord", ParentId = 244, Icon = "", Enable = 1, TableName = "MES_DefectiveProductRecord", Permission = new List<string> { "Search", "Export" } },
                new MenuItemDto { Id = 280, Name = "排班日历", Url = "MES_Calendar", ParentId = 242, Icon = "", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 266, Name = "工序统计", Url = "/MES_ProcessReport", ParentId = 241, Icon = "", Enable = 1, TableName = "MES_ProcessReport", Permission = new List<string> { "Search", "Export", "Print" } },
                new MenuItemDto { Id = 270, Name = "变更记录", Url = "/MES_ProductionPlanChangeRecord", ParentId = 239, Icon = "", Enable = 1, TableName = "MES_ProductionPlanChangeRecord", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 258, Name = "产品入库", Url = "/MES_ProductInbound", ParentId = 237, Icon = "", Enable = 1, TableName = "MES_ProductInbound", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 251, Name = "产线管理", Url = "/MES_ProductionLine", ParentId = 236, Icon = "", Enable = 1, TableName = "MES_ProductionLine", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 302, Name = "移动端开发", Url = "http://app.volcore.xyz/", ParentId = 32, Icon = "el-icon-mobile-phone", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 254, Name = "物料分类", Url = "/MES_MaterialCatalog", ParentId = 236, Icon = "", Enable = 1, TableName = "MES_MaterialCatalog", Permission = new List<string> { "Search", "Add", "Delete", "Update" } },
                new MenuItemDto { Id = 253, Name = "物料管理", Url = "/MES_Material", ParentId = 236, Icon = "", Enable = 1, TableName = "MES_Material", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Print" } },
                new MenuItemDto { Id = 277, Name = "质检记录", Url = "/MES_QualityInspectionRecord", ParentId = 240, Icon = "", Enable = 1, TableName = "MES_QualityInspectionRecord", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 289, Name = "生产任务", Url = "/list", ParentId = 239, Icon = "", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 263, Name = "设备故障", Url = "/MES_EquipmentFaultRecord", ParentId = 238, Icon = "", Enable = 1, TableName = "MES_EquipmentFaultRecord", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import", "Export" } },
                new MenuItemDto { Id = 259, Name = "产品出库", Url = "/MES_ProductOutbound", ParentId = 237, Icon = "", Enable = 1, TableName = "MES_ProductOutbound", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 287, Name = "制造BOM", Url = "/MES_Bom_Main", ParentId = 286, Icon = "", Enable = 1, TableName = "MES_Bom_Main", Permission = new List<string> { "Search", "Add", "Delete", "Update", "CopyData", "Export" } },
                new MenuItemDto { Id = 107, Name = "表单设计", Url = "/formDraggable", ParentId = 106, Icon = "", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 65, Name = "代码生成", Url = "/coder", ParentId = 64, Icon = "", Enable = 1, TableName = "/", Permission = new List<string> { "Search", "Add", "Delete", "Update" } },
                new MenuItemDto { Id = 318, Name = "批号", Url = "/BD_LotName", ParentId = 317, Icon = "el-icon-wind-power", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import", "Export", "Upload" } },
                new MenuItemDto { Id = 319, Name = "等级", Url = "/BD_Grade", ParentId = 317, Icon = "el-icon-finished", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import", "Export", "Upload" } },
                new MenuItemDto { Id = 320, Name = "板材", Url = "/BD_Pallet", ParentId = 317, Icon = "el-icon-receiving", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import", "Export", "Upload" } },
                new MenuItemDto { Id = 316, Name = "PLC数据查看", Url = "/machinePre", ParentId = 315, Icon = "el-icon-s-finance", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Import", "Export" } },
                new MenuItemDto { Id = 322, Name = "预测性维护测试", Url = "/machinePretest", ParentId = 315, Icon = "el-icon-set-up", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Import", "Export" } },
                new MenuItemDto { Id = 323, Name = "AI助手", Url = "/AIChat", ParentId = 315, Icon = "el-icon-chat-dot-round", Enable = 1, TableName = ".", Permission = new List<string>() },
                new MenuItemDto { Id = 311, Name = "丝车降等", Url = "/SpinDowmGrade", ParentId = 306, Icon = "el-icon-bottom", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Delete", "Import", "Export" } },
                new MenuItemDto { Id = 313, Name = "打印设计", Url = "/PrintDesgin", ParentId = 305, Icon = "bi-pc-display-horizontal", Enable = 1, TableName = ".", Permission = new List<string>() },
                new MenuItemDto { Id = 314, Name = "打印主页", Url = "/PrintHome", ParentId = 305, Icon = "el-icon-receiving", Enable = 1, TableName = ".", Permission = new List<string>() },
                new MenuItemDto { Id = 321, Name = "PLC数据", Url = "/PLCValue", ParentId = 305, Icon = "bi-align-middle", Enable = 1, TableName = ".", Permission = new List<string>() },
                new MenuItemDto { Id = 310, Name = "丝车页面", Url = "/carMasterHome", ParentId = 305, Icon = "el-icon-connection", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import", "Export" } },
                new MenuItemDto { Id = 312, Name = "任务报表", Url = "/CustomTableDemo", ParentId = 303, Icon = "el-icon-goods", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Import", "Export" } },
                new MenuItemDto { Id = 304, Name = "任务添加", Url = "/BD_TASK_INFO", ParentId = 303, Icon = "el-icon-s-grid", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Add", "Delete", "Update" } },
                new MenuItemDto { Id = 290, Name = "Bom明细", Url = "/MES_Bom_Detail", ParentId = 286, Icon = "", Enable = 2, TableName = "MES_Bom_Detail", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import", "Export" } },
                new MenuItemDto { Id = 262, Name = "设备保养", Url = "/MES_EquipmentMaintenance", ParentId = 238, Icon = "", Enable = 1, TableName = "MES_EquipmentMaintenance", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 138, Name = "任务配置", Url = "/Sys_QuartzOptions", ParentId = 137, Icon = "", Enable = 1, TableName = "Sys_QuartzOptions", Permission = new List<string> { "Search", "Add", "Delete", "Update" } },
                new MenuItemDto { Id = 139, Name = "执行记录", Url = "/Sys_QuartzLog", ParentId = 137, Icon = "", Enable = 1, TableName = "Sys_QuartzLog", Permission = new List<string> { "Search", "Delete", "Export" } },
                new MenuItemDto { Id = 134, Name = "流程管理", Url = "/Sys_WorkFlow", ParentId = 133, Icon = "", Enable = 1, TableName = "Sys_WorkFlow", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Export" } },
                new MenuItemDto { Id = 135, Name = "我的审批", Url = "/Sys_WorkFlowTable", ParentId = 133, Icon = "", Enable = 1, TableName = "Sys_WorkFlowTable", Permission = new List<string> { "Search", "Delete" } },
                new MenuItemDto { Id = 136, Name = "发起流程", Url = "/flowdemo", ParentId = 133, Icon = "", Enable = 1, TableName = "发起流程", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 109, Name = "表单配置", Url = "/FormDesignOptions", ParentId = 106, Icon = "", Enable = 1, TableName = "FormDesignOptions", Permission = new List<string> { "Search", "Add", "Delete", "Update" } },
                new MenuItemDto { Id = 110, Name = "数据采集", Url = "/formCollectionResultTree", ParentId = 106, Icon = "", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Delete", "Export" } },
                new MenuItemDto { Id = 317, Name = "基础信息", Url = ".", ParentId = 61, Icon = "el-icon-copy-document", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 303, Name = "任务页面", Url = "", ParentId = 45, Icon = "bi-box-seam-fill", Enable = 1, TableName = ".", Permission = new List<string> { "Search", "Add", "Delete", "Update", "Import", "Export" } },
                new MenuItemDto { Id = 6, Name = "系统日志", Url = "/Sys_Log", ParentId = 5, Icon = "", Enable = 1, TableName = "Sys_Log", Permission = new List<string> { "Search", "Delete", "Export" } },
                new MenuItemDto { Id = 45, Name = "包装模块", Url = null, ParentId = 0, Icon = "bi-pip-fill", Enable = 1, TableName = ".", Permission = new List<string>() },
                new MenuItemDto { Id = 305, Name = "落筒模块", Url = "", ParentId = 0, Icon = "el-icon-s-management", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 306, Name = "外检模块", Url = "", ParentId = 0, Icon = "el-icon-scissors", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } },
                new MenuItemDto { Id = 315, Name = "预测性模块", Url = ".", ParentId = 0, Icon = "el-icon-s-opportunity", Enable = 1, TableName = ".", Permission = new List<string> { "Search" } }
            };
        }
    }
}
